name: fakrny
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  responsive_sizer: ^3.3.1
  flutter_svg: ^2.2.2
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  curved_labeled_navigation_bar: ^2.0.6
  image_picker: ^1.2.1
  camera: ^0.11.3
  table_calendar: ^3.2.0
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: SfPro
      fonts:
        - asset: assets/fonts/sf_pro_regular.otf
          weight: 400
        - asset: assets/fonts/sf_pro_medium.otf
          weight: 500
        - asset: assets/fonts/sf_pro_bold.otf
          weight: 700
        - asset: assets/fonts/sf_pro_italic.otf
          style: italic
